Repository pivotal-cf/docs-identity, pull requests merged in 2019-04, with the labels that each got.

#123 Reviewed 1.9 doc updates
  configure-apps/index.html.md.erb
Labels: unscheduled

#124 add release notes for SSO 1.7.4
  index.html.md.erb
  release-notes.html.md.erb
Labels: in progress

#125 add release notes for SSO 1.8.3 [#165299063]
  index.html.md.erb
  release-notes.html.md.erb
Labels: unscheduled

#126 Correct instructions on using API to configure SSO Service plan [#165…
  manage-service-plans-api.html.md.erb
Labels: unscheduled

#127 Improve saml integration docs
  adfs/config-sso.html.md.erb
  configure-id-providers.html.md.erb
Labels: scheduled
